# Generated by Django 2.2.12 on 2021-03-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='用户名')),
                ('nickname', models.CharField(default=models.CharField(max_length=11, verbose_name='用户名'), max_length=30, verbose_name='nickname')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
        migrations.CreateModel(
            name='Orgnization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=30, verbose_name='机构名称')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
