# Generated by Django 2.2.12 on 2021-03-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=30, verbose_name='考试名称')),
                ('type', models.CharField(max_length=20, verbose_name='科目类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('total_time', models.CharField(max_length=10, verbose_name='考试时间')),
                ('choice_num', models.IntegerField(verbose_name='选择题数量')),
                ('fill_num', models.IntegerField(verbose_name='填空题数量')),
                ('total_score', models.IntegerField(verbose_name='总分')),
                ('status', models.BooleanField(verbose_name='考试状态')),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.BankInformation')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Orgnization')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(max_length=10, verbose_name='题型')),
                ('question_id', models.IntegerField(verbose_name='题目id')),
                ('answer', models.CharField(max_length=50, verbose_name='考生答案')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
